# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('event_image', models.ImageField(blank=True, upload_to='event_images/')),
                ('price', models.IntegerField(blank=True)),
                ('total_seats', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('post', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=20)),
                ('amount_paid', models.CharField(max_length=20)),
                ('qrcode', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('confirm_image', models.ImageField(blank=True, upload_to='confirm_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventUsers')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=30, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Table'),
        ),
        migrations.AddField(
            model_name='eventusers',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Table'),
        ),
    ]
