# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170803_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='qrcode',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventusers',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='eventusers',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eventusers',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eventusers',
            name='post',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
